#!/usr/bin/env python3
"""Generate indexes and validate the LeetCode C learning archive."""

from __future__ import annotations

import argparse
import os
import re
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import unquote


ROOT = Path(__file__).resolve().parents[1]
PROBLEMS = ROOT / "problems"
ATTEMPTS = ROOT / "attempts"
DOCS = ROOT / "docs"
GENERATED_NOTE = "<!-- Generated by scripts/generate_indexes.py. Do not edit by hand. -->"
SNAPSHOT_START = "<!-- snapshot:start -->"
SNAPSHOT_END = "<!-- snapshot:end -->"
NAV_MARKER = "<!-- repository-navigation -->"
TECHNIQUE_COVERAGE_START = "<!-- technique-topic-coverage:start -->"
TECHNIQUE_COVERAGE_END = "<!-- technique-topic-coverage:end -->"
FOLDER_RE = re.compile(r"^(\d{4})-([a-z0-9]+(?:-[a-z0-9]+)*)$")
TITLE_RE = re.compile(r"^# #(\d{1,4}) - (.+)$", re.MULTILINE)
FIELD_RE = re.compile(r"^- ([A-Za-z ]+):\s*(.+)$", re.MULTILINE)
LINK_RE = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
IGNORED_PARTS = {".git", "tmp", "tools"}
TECHNIQUE_SLUGS = (
    "01-brute-force-and-enumeration",
    "02-linear-scan-and-indexing",
    "03-simulation-and-state-machines",
    "04-counting-and-frequency-tables",
    "05-hash-tables",
    "06-two-pointers",
    "07-in-place-read-write",
    "08-fixed-sliding-window",
    "09-variable-sliding-window",
    "10-prefix-sums",
    "11-prefix-state-xor-and-product",
    "12-difference-arrays-and-event-sweeps",
    "13-binary-search-on-sorted-data",
    "14-binary-search-on-answer",
    "15-sorting-and-buckets",
    "16-divide-conquer-and-selection",
    "17-greedy",
    "18-intervals",
    "19-stack",
    "20-monotonic-stack",
    "21-queue-and-circular-buffer",
    "22-monotonic-queue",
    "23-heap-and-top-k",
    "24-streams-and-iterators",
    "25-stateful-apis-design-and-ownership",
    "26-linked-list-rewiring",
    "27-fast-and-slow-pointers",
    "28-recursion-and-backtracking",
    "29-tree-and-graph-traversal",
    "30-dynamic-programming-and-kadane",
    "31-bitwise-xor-and-number-theory",
    "32-strings-parsing-and-pattern-matching",
    "33-matrix-traversal-and-directions",
    "34-matrix-neighborhoods-and-in-place-state",
    "35-2d-prefix-sum-and-image-regions",
)
REQUIRED_ROOT_FILES = {
    "README.md",
    "README_TR.md",
    "docs/LEARNING_ROADMAP.md",
    "docs/PROBLEM_INDEX.md",
    "docs/TOPIC_INDEX.md",
    "docs/PRACTICE_TRACKS.md",
    "docs/ATTEMPTS.md",
    "docs/ADDING_A_PROBLEM.md",
    "docs/techniques/README.md",
    "docs/techniques/en/README.md",
    "docs/techniques/tr/README.md",
    *{
        f"docs/techniques/{language}/{slug}.md"
        for language in ("en", "tr")
        for slug in TECHNIQUE_SLUGS
    },
}
ROOT_README_DESTINATIONS = {
    "README_TR.md",
    "docs/LEARNING_ROADMAP.md",
    "docs/PROBLEM_INDEX.md",
    "docs/TOPIC_INDEX.md",
    "docs/PRACTICE_TRACKS.md",
    "docs/ATTEMPTS.md",
    "docs/techniques/en/README.md",
}
TRACK_EXPECTATIONS = {
    "Bitwise / Embedded Essentials": 39,
    "Matrix / 2D Array Essentials": 12,
    "Data Structure Design Essentials": 14,
}
ROADMAP_ROW_RE = re.compile(
    r"^\|\s*(\d+)\s*\|\s*\[x\]\s*\[#(\d{4})[^]]*]\(\.\./problems/([^)]+)\)\s*\|",
    re.MULTILINE | re.IGNORECASE,
)
TRACK_ROW_RE = re.compile(
    r"^\|\s*(\d+)\s*\|\s*\[#(\d{4})[^]]*]\(\.\./problems/([^)]+)\)\s*\|",
    re.MULTILINE,
)
HEADING_RE = re.compile(r"^#{1,6}\s+(.+?)\s*$", re.MULTILINE)
MOJIBAKE_MARKERS = (
    "\ufffd",
    "\u00c3",
    "\u00c2",
    "\u00c4\u00b0",
    "\u00c5",
    "\u00e2\u20ac",
)
TITLE_SLUG_EXCEPTIONS = {69: "sqrtx"}


@dataclass(frozen=True)
class Problem:
    number: int
    number_text: str
    name: str
    folder: str
    difficulty: str
    topics: tuple[str, ...]
    solved: str
    source: str
    approach: str

    @property
    def primary_topic(self) -> str:
        return self.topics[0]


def clean_cell(value: str) -> str:
    return " ".join(value.replace("|", "\\|").split())


def title_slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def parse_problem(directory: Path) -> tuple[Problem | None, list[str]]:
    errors: list[str] = []
    folder_match = FOLDER_RE.fullmatch(directory.name)
    if not folder_match:
        return None, [f"invalid problem folder name: {directory.name}"]

    readme = directory / "README.md"
    solution = directory / "solution.c"
    if not readme.exists():
        errors.append(f"missing README.md: {directory.relative_to(ROOT)}")
    if not solution.exists():
        errors.append(f"missing solution.c: {directory.relative_to(ROOT)}")
    if errors:
        return None, errors

    text = readme.read_text(encoding="utf-8")
    title_match = TITLE_RE.search(text)
    if not title_match:
        return None, [f"invalid title: {readme.relative_to(ROOT)}"]

    folder_number = folder_match.group(1)
    if int(title_match.group(1)) != int(folder_number):
        errors.append(f"title/folder number mismatch: {readme.relative_to(ROOT)}")
    expected_folder_slug = TITLE_SLUG_EXCEPTIONS.get(int(folder_number), title_slug(title_match.group(2)))
    if folder_match.group(2) != expected_folder_slug:
        errors.append(f"title/folder slug mismatch: {readme.relative_to(ROOT)}")

    fields = {key.strip().lower(): value.strip() for key, value in FIELD_RE.findall(text)}
    required = ("status", "difficulty", "topics", "hint")
    for key in required:
        if not fields.get(key):
            errors.append(f"missing {key} metadata: {readme.relative_to(ROOT)}")

    solved = fields.get("solved date") or fields.get("solved")
    source = fields.get("source") or fields.get("leetcode")
    if not solved:
        errors.append(f"missing solved date: {readme.relative_to(ROOT)}")
    if not source:
        errors.append(f"missing source URL: {readme.relative_to(ROOT)}")
    expected_source = f"https://leetcode.com/problems/{folder_match.group(2)}/"
    if source and source != expected_source:
        errors.append(f"incorrect source URL: {readme.relative_to(ROOT)} -> {source}")
    if fields.get("status", "").lower() not in {"solved", "accepted"}:
        errors.append(f"problem is not marked accepted: {readme.relative_to(ROOT)}")
    if fields.get("difficulty") not in {"Easy", "Medium", "Hard"}:
        errors.append(f"invalid difficulty: {readme.relative_to(ROOT)}")
    if solved and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", solved):
        errors.append(f"invalid solved date: {readme.relative_to(ROOT)} -> {solved}")

    topics = tuple(topic.strip() for topic in fields.get("topics", "").split(",") if topic.strip())
    if not topics:
        errors.append(f"empty topics metadata: {readme.relative_to(ROOT)}")
    if errors:
        return None, errors

    return (
        Problem(
            number=int(folder_number),
            number_text=folder_number,
            name=title_match.group(2).strip(),
            folder=directory.name,
            difficulty=fields["difficulty"],
            topics=topics,
            solved=solved,
            source=source,
            approach=fields["hint"],
        ),
        [],
    )


def load_problems() -> tuple[list[Problem], list[str]]:
    problems: list[Problem] = []
    errors: list[str] = []
    seen: dict[int, str] = {}
    for directory in sorted(path for path in PROBLEMS.iterdir() if path.is_dir()):
        problem, problem_errors = parse_problem(directory)
        errors.extend(problem_errors)
        if problem is None:
            continue
        if problem.number in seen:
            errors.append(
                f"duplicate problem number #{problem.number_text}: {seen[problem.number]} and {problem.folder}"
            )
        else:
            seen[problem.number] = problem.folder
        problems.append(problem)
    problems.sort(key=lambda item: item.number)
    return problems, errors


def normalize_problem_pages() -> None:
    footer = (
        f"\n\n---\n\n{NAV_MARKER}\n"
        "[C solution](solution.c) | "
        "[Repository home](../../README.md) | "
        "[Problem index](../../docs/PROBLEM_INDEX.md) | "
        "[Topic index](../../docs/TOPIC_INDEX.md) | "
        "[Practice tracks](../../docs/PRACTICE_TRACKS.md)\n"
    )
    for directory in sorted(path for path in PROBLEMS.iterdir() if path.is_dir()):
        readme = directory / "README.md"
        if not readme.exists():
            continue
        text = readme.read_text(encoding="utf-8")
        title_match = TITLE_RE.search(text)
        folder_match = FOLDER_RE.fullmatch(directory.name)
        if title_match and folder_match:
            normalized_title = f"# #{folder_match.group(1)} - {title_match.group(2)}"
            text = text[: title_match.start()] + normalized_title + text[title_match.end() :]
        text = re.sub(r"^- Status: Solved\s*$", "- Status: Accepted", text, count=1, flags=re.MULTILINE)
        text = re.sub(r"^- Solved:\s*", "- Solved date: ", text, count=1, flags=re.MULTILINE)
        text = re.sub(r"^- LeetCode:\s*", "- Source: ", text, count=1, flags=re.MULTILINE)
        text = re.sub(r"^- Companies:.*\n?", "", text, count=1, flags=re.MULTILINE)
        if folder_match:
            canonical_source = f"- Source: https://leetcode.com/problems/{folder_match.group(2)}/"
            text = re.sub(r"^- Source:.*$", canonical_source, text, count=1, flags=re.MULTILINE)
        if NAV_MARKER in text:
            text = text.split(NAV_MARKER, 1)[0]
            text = re.sub(r"\n---\s*$", "", text.rstrip())
        text = text.rstrip() + footer
        readme.write_text(text, encoding="utf-8", newline="\n")


def render_problem_index(problems: list[Problem], attempt_count: int) -> str:
    distribution = Counter(problem.difficulty for problem in problems)
    lines = [
        GENERATED_NOTE,
        "# Problem Index",
        "",
        "[Repository home](../README.md) | [Learning roadmap](LEARNING_ROADMAP.md) | "
        "[Topic index](TOPIC_INDEX.md) | [Technique guide](techniques/en/README.md) | "
        "[Practice tracks](PRACTICE_TRACKS.md)",
        "",
        "This is the canonical archive of accepted solutions. Attempts are counted separately.",
        "",
        f"Accepted: **{len(problems)}** | Easy: **{distribution['Easy']}** | "
        f"Medium: **{distribution['Medium']}** | Hard: **{distribution['Hard']}** | "
        f"Open attempts: **{attempt_count}**",
        "",
    ]
    ranges = ((0, 999), (1000, 1999), (2000, 2999), (3000, 9999))
    for start, end in ranges:
        group = [problem for problem in problems if start <= problem.number <= end]
        if not group:
            continue
        lines.extend(
            [
                f"<details{' open' if start == 0 else ''}>",
                f"<summary>#{start:04d}-#{end:04d} ({len(group)} problems)</summary>",
                "",
                "| # | Problem | Difficulty | Primary topic | Approach | Solved |",
                "| ---: | --- | --- | --- | --- | --- |",
            ]
        )
        for problem in group:
            lines.append(
                f"| #{problem.number_text} | [{clean_cell(problem.name)}](../problems/{problem.folder}) | "
                f"{clean_cell(problem.difficulty)} | {clean_cell(problem.primary_topic)} | "
                f"{clean_cell(problem.approach)} | {clean_cell(problem.solved)} |"
            )
        lines.extend(["", "</details>", ""])
    return "\n".join(lines).rstrip() + "\n"


def render_topic_index(problems: list[Problem]) -> str:
    by_topic: dict[str, list[Problem]] = defaultdict(list)
    for problem in problems:
        for topic in dict.fromkeys(problem.topics):
            by_topic[topic].append(problem)

    lines = [
        GENERATED_NOTE,
        "# Topic Index",
        "",
        "[Repository home](../README.md) | [Problem index](PROBLEM_INDEX.md) | "
        "[Learning roadmap](LEARNING_ROADMAP.md) | [Technique guide](techniques/en/README.md) | "
        "[Practice tracks](PRACTICE_TRACKS.md)",
        "",
        "Problems appear under the focused topic tags recorded in their README metadata.",
        "",
    ]
    for topic in sorted(by_topic, key=str.casefold):
        group = sorted(by_topic[topic], key=lambda item: item.number)
        lines.extend(
            [
                "<details>",
                f"<summary>{topic} ({len(group)})</summary>",
                "",
                "| # | Problem | Difficulty | Solved |",
                "| ---: | --- | --- | --- |",
            ]
        )
        for problem in group:
            lines.append(
                f"| #{problem.number_text} | [{clean_cell(problem.name)}](../problems/{problem.folder}) | "
                f"{clean_cell(problem.difficulty)} | {clean_cell(problem.solved)} |"
            )
        lines.extend(["", "</details>", ""])
    return "\n".join(lines).rstrip() + "\n"


def render_snapshot(problems: list[Problem], attempt_count: int, roadmap_count: int) -> str:
    distribution = Counter(problem.difficulty for problem in problems)
    return "\n".join(
        [
            SNAPSHOT_START,
            "| Item | Current value |",
            "| --- | ---: |",
            f"| Accepted solutions | {len(problems)} |",
            f"| Easy / Medium / Hard | {distribution['Easy']} / {distribution['Medium']} / {distribution['Hard']} |",
            f"| First 100 roadmap | {roadmap_count} accepted |",
            "| Focused practice tracks | 3 |",
            f"| Open attempts | {attempt_count} |",
            "| Primary language | C |",
            SNAPSHOT_END,
        ]
    )


def replace_snapshot(readme: str, snapshot: str) -> str:
    pattern = re.compile(re.escape(SNAPSHOT_START) + r".*?" + re.escape(SNAPSHOT_END), re.DOTALL)
    if not pattern.search(readme):
        raise ValueError("README snapshot markers are missing")
    return pattern.sub(snapshot, readme)


def validate_attempts() -> tuple[int, list[str]]:
    errors: list[str] = []
    directories = sorted(path for path in ATTEMPTS.iterdir() if path.is_dir())
    for directory in directories:
        if not FOLDER_RE.fullmatch(directory.name):
            errors.append(f"invalid attempt folder name: {directory.name}")
        for required in ("README.md", "attempt.c"):
            if not (directory / required).exists():
                errors.append(f"missing {required}: {directory.relative_to(ROOT)}")
        readme = directory / "README.md"
        if readme.exists():
            text = readme.read_text(encoding="utf-8")
            if "- Result: Time Limit Exceeded" not in text or "- Status: Not solved" not in text:
                errors.append(f"attempt status is not explicit: {readme.relative_to(ROOT)}")

    attempts_doc = (DOCS / "ATTEMPTS.md").read_text(encoding="utf-8")
    documented = set(re.findall(r"\.\./attempts/([^/)]+)/?", attempts_doc))
    actual = {directory.name for directory in directories}
    for folder in sorted(actual - documented):
        errors.append(f"attempt missing from docs/ATTEMPTS.md: {folder}")
    for folder in sorted(documented - actual):
        errors.append(f"docs/ATTEMPTS.md references missing attempt: {folder}")
    return len(directories), errors


def validate_roadmap() -> tuple[int, list[str]]:
    text = (DOCS / "LEARNING_ROADMAP.md").read_text(encoding="utf-8")
    rows = [(int(order), int(number), folder) for order, number, folder in ROADMAP_ROW_RE.findall(text)]
    errors: list[str] = []
    orders = [order for order, _, _ in rows]
    numbers = [number for _, number, _ in rows]
    folders = [folder for _, _, folder in rows]
    if orders != list(range(1, 101)):
        errors.append("learning roadmap must contain ordered entries 1..100 exactly once")
    if len(numbers) != len(set(numbers)):
        errors.append("learning roadmap contains duplicate problem numbers")
    if len(folders) != len(set(folders)):
        errors.append("learning roadmap contains duplicate problem folders")
    for _, number, folder in rows:
        if not folder.startswith(f"{number:04d}-") or not (PROBLEMS / folder).is_dir():
            errors.append(f"invalid learning roadmap target: #{number:04d} -> {folder}")
    return len(rows), errors


def validate_practice_tracks() -> tuple[dict[str, int], list[str]]:
    text = (DOCS / "PRACTICE_TRACKS.md").read_text(encoding="utf-8")
    errors: list[str] = []
    counts: dict[str, int] = {}
    for title, expected in TRACK_EXPECTATIONS.items():
        match = re.search(
            rf"^## {re.escape(title)}\s*$\n(.*?)(?=^## |\Z)",
            text,
            flags=re.MULTILINE | re.DOTALL,
        )
        if not match:
            errors.append(f"missing practice track: {title}")
            counts[title] = 0
            continue
        rows = [(int(order), int(number), folder) for order, number, folder in TRACK_ROW_RE.findall(match.group(1))]
        counts[title] = len(rows)
        if [order for order, _, _ in rows] != list(range(1, expected + 1)):
            errors.append(f"practice track order/count mismatch: {title}")
        identities = [(number, folder) for _, number, folder in rows]
        if len(identities) != len(set(identities)):
            errors.append(f"duplicate problem inside practice track: {title}")
        for _, number, folder in rows:
            if not folder.startswith(f"{number:04d}-") or not (PROBLEMS / folder).is_dir():
                errors.append(f"invalid practice track target: {title} #{number:04d} -> {folder}")
    return counts, errors


def repository_markdown() -> list[Path]:
    return [
        path
        for path in ROOT.rglob("*.md")
        if not any(part in IGNORED_PARTS for part in path.relative_to(ROOT).parts)
    ]


def normalize_local_target(source: Path, target: str) -> tuple[Path | None, str]:
    path_part = unquote(target.split("#", 1)[0])
    if not path_part:
        return source, ""
    candidate = Path(os.path.normpath(source.parent / path_part))
    try:
        relative = candidate.relative_to(ROOT)
    except ValueError:
        return None, path_part
    return ROOT / relative, relative.as_posix()


def has_exact_case(relative_path: str) -> bool:
    current = ROOT
    for part in Path(relative_path).parts:
        if not current.is_dir():
            return False
        matches = [child.name for child in current.iterdir() if child.name.lower() == part.lower()]
        if part not in matches:
            return False
        current /= part
    return True


def heading_anchor(heading: str) -> str:
    heading = re.sub(r"[`*_~]", "", heading.strip().lower())
    heading = re.sub(r"[^\w\- ]", "", heading, flags=re.UNICODE)
    return re.sub(r"\s+", "-", heading)


def anchor_exists(path: Path, anchor: str) -> bool:
    if not anchor or path.suffix.lower() != ".md":
        return True
    anchors: Counter[str] = Counter()
    for heading in HEADING_RE.findall(path.read_text(encoding="utf-8")):
        base = heading_anchor(heading)
        occurrence = anchors[base]
        anchors[base] += 1
        actual = base if occurrence == 0 else f"{base}-{occurrence}"
        if actual == unquote(anchor).lower():
            return True
    return False


def validate_links() -> list[str]:
    errors: list[str] = []
    for source in repository_markdown():
        text = source.read_text(encoding="utf-8")
        relative_source = source.relative_to(ROOT)
        if re.search(r"C:[/\\]Users[/\\]", text, flags=re.IGNORECASE) or "file://" in text.lower():
            errors.append(f"local filesystem path in Markdown: {relative_source}")
        if "ROADMAP.md" in text and "LEARNING_ROADMAP.md" not in text:
            errors.append(f"obsolete ROADMAP.md reference: {relative_source}")
        if "SOLVED_PROBLEMS.md" in text:
            errors.append(f"obsolete SOLVED_PROBLEMS.md reference: {relative_source}")
        for raw_target in LINK_RE.findall(text):
            target = raw_target.strip().split(maxsplit=1)[0].strip("<>") if raw_target.strip() else ""
            if not target:
                errors.append(f"empty Markdown link: {relative_source}")
                continue
            if "\\" in target:
                errors.append(f"backslash in Markdown link: {relative_source} -> {target}")
            if target.startswith(("http://", "https://", "mailto:")):
                continue
            path, relative_target = normalize_local_target(source, target)
            if path is None or not path.exists():
                errors.append(f"broken link: {relative_source} -> {target}")
                continue
            if relative_target and not has_exact_case(relative_target):
                errors.append(f"link path has incorrect letter case: {relative_source} -> {target}")
            if "#" in target and not anchor_exists(path, target.split("#", 1)[1]):
                errors.append(f"missing Markdown anchor: {relative_source} -> {target}")
    return errors


def validate_encoding() -> list[str]:
    errors: list[str] = []
    suffixes = {".c", ".h", ".md", ".py", ".yml", ".yaml"}
    for path in ROOT.rglob("*"):
        if not path.is_file() or any(part in IGNORED_PARTS for part in path.relative_to(ROOT).parts):
            continue
        if path.suffix not in suffixes:
            continue
        data = path.read_bytes()
        if data.startswith(b"\xef\xbb\xbf"):
            errors.append(f"UTF-8 BOM found: {path.relative_to(ROOT)}")
        without_crlf = data.replace(b"\r\n", b"")
        if b"\r" in without_crlf or (b"\r\n" in data and b"\n" in without_crlf):
            errors.append(f"mixed or invalid line endings: {path.relative_to(ROOT)}")
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError as exc:
            errors.append(f"invalid UTF-8: {path.relative_to(ROOT)} ({exc})")
            continue
        if any(marker in text for marker in MOJIBAKE_MARKERS):
            errors.append(f"possible mojibake text: {path.relative_to(ROOT)}")
    return errors


def validate_normalized_pages() -> list[str]:
    errors: list[str] = []
    for directory in sorted(path for path in PROBLEMS.iterdir() if path.is_dir()):
        readme = directory / "README.md"
        if not readme.exists():
            continue
        text = readme.read_text(encoding="utf-8")
        if "- Status: Accepted" not in text:
            errors.append(f"non-standard status metadata: {readme.relative_to(ROOT)}")
        if "- Solved date:" not in text:
            errors.append(f"non-standard solved date metadata: {readme.relative_to(ROOT)}")
        if "- Source:" not in text:
            errors.append(f"non-standard source metadata: {readme.relative_to(ROOT)}")
        if NAV_MARKER not in text:
            errors.append(f"missing repository navigation: {readme.relative_to(ROOT)}")
        if "[C solution](solution.c)" not in text:
            errors.append(f"missing solution.c link: {readme.relative_to(ROOT)}")
        if "TR:" not in text or "EN:" not in text:
            errors.append(f"missing bilingual problem summary: {readme.relative_to(ROOT)}")
        if re.search(r"\b(?:TODO|TBD|placeholder|fill this|coming soon)\b", text, re.IGNORECASE):
            errors.append(f"placeholder text remains: {readme.relative_to(ROOT)}")
    return errors


def validate_root_documents() -> list[str]:
    errors = [
        f"missing required repository file: {path}"
        for path in sorted(REQUIRED_ROOT_FILES)
        if not (ROOT / path).is_file()
    ]
    root_text = (ROOT / "README.md").read_text(encoding="utf-8")
    targets = {
        raw.strip().split(maxsplit=1)[0].strip("<>").split("#", 1)[0]
        for raw in LINK_RE.findall(root_text)
        if raw.strip()
    }
    for destination in sorted(ROOT_README_DESTINATIONS - targets):
        errors.append(f"root README does not link to required destination: {destination}")
    for generated in (DOCS / "PROBLEM_INDEX.md", DOCS / "TOPIC_INDEX.md"):
        if generated.is_file() and not generated.read_text(encoding="utf-8").startswith(GENERATED_NOTE):
            errors.append(f"generated notice missing: {generated.relative_to(ROOT)}")
    return errors


def validate_technique_coverage(problems: list[Problem]) -> list[str]:
    guide = DOCS / "techniques" / "README.md"
    if not guide.is_file():
        return ["missing technique guide: docs/techniques/README.md"]

    text = guide.read_text(encoding="utf-8")
    if TECHNIQUE_COVERAGE_START not in text or TECHNIQUE_COVERAGE_END not in text:
        return ["technique guide topic coverage markers are missing"]

    block = text.split(TECHNIQUE_COVERAGE_START, 1)[1].split(TECHNIQUE_COVERAGE_END, 1)[0]
    documented = set(re.findall(r"`([^`\n]+)`", block))
    expected = {topic for problem in problems for topic in problem.topics}
    errors: list[str] = []

    for topic in sorted(expected - documented, key=str.casefold):
        errors.append(f"technique guide does not cover topic: {topic}")
    for topic in sorted(documented - expected, key=str.casefold):
        errors.append(f"technique guide lists unknown topic: {topic}")

    expected_count = f"Coverage total: **{len(expected)} / {len(expected)} current topic labels**."
    if expected_count not in text:
        errors.append("technique guide topic coverage count is stale")
    return errors


def validate_technique_structure() -> list[str]:
    base = DOCS / "techniques"
    expected_names = {"README.md", *(f"{slug}.md" for slug in TECHNIQUE_SLUGS)}
    errors: list[str] = []

    for language in ("en", "tr"):
        directory = base / language
        actual_names = {path.name for path in directory.glob("*.md")} if directory.is_dir() else set()
        for name in sorted(expected_names - actual_names):
            errors.append(f"missing {language} technique chapter: docs/techniques/{language}/{name}")
        for name in sorted(actual_names - expected_names):
            errors.append(f"unexpected {language} technique chapter: docs/techniques/{language}/{name}")

    for number, slug in enumerate(TECHNIQUE_SLUGS, start=1):
        for language, counterpart, theory_heading, practice_heading in (
            ("en", "tr", "## Mental Model", "## Practice In This Repository"),
            ("tr", "en", "## Zihinsel Model", "## Bu Repoda Çalış"),
        ):
            chapter = base / language / f"{slug}.md"
            if not chapter.is_file():
                continue
            text = chapter.read_text(encoding="utf-8")
            relative = chapter.relative_to(ROOT)
            if not text.startswith(f"# {number:02d} - "):
                errors.append(f"technique chapter number/title mismatch: {relative}")
            if theory_heading not in text:
                errors.append(f"theory-first heading missing: {relative}")
            if practice_heading not in text:
                errors.append(f"repository practice heading missing: {relative}")
            if f"(../{counterpart}/{slug}.md)" not in text:
                errors.append(f"counterpart language link missing: {relative}")
            if len(text.splitlines()) < 35:
                errors.append(f"technique chapter is too shallow: {relative}")
    return errors


def write_or_check(path: Path, expected: str, check: bool, errors: list[str]) -> None:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            errors.append(f"generated file is stale: {path.relative_to(ROOT)}")
    else:
        path.write_text(expected, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="validate without writing")
    args = parser.parse_args()

    if not args.check:
        normalize_problem_pages()

    problems, errors = load_problems()
    errors.extend(validate_technique_coverage(problems))
    errors.extend(validate_technique_structure())
    attempt_count, attempt_errors = validate_attempts()
    errors.extend(attempt_errors)
    count, roadmap_errors = validate_roadmap()
    errors.extend(roadmap_errors)
    if count != 100:
        errors.append(f"learning roadmap must contain 100 accepted entries, found {count}")
    track_counts, track_errors = validate_practice_tracks()
    errors.extend(track_errors)

    problem_index = render_problem_index(problems, attempt_count)
    topic_index = render_topic_index(problems)
    write_or_check(DOCS / "PROBLEM_INDEX.md", problem_index, args.check, errors)
    write_or_check(DOCS / "TOPIC_INDEX.md", topic_index, args.check, errors)

    readme_path = ROOT / "README.md"
    if readme_path.exists():
        try:
            expected_readme = replace_snapshot(
                readme_path.read_text(encoding="utf-8"),
                render_snapshot(problems, attempt_count, count),
            )
            write_or_check(readme_path, expected_readme, args.check, errors)
        except ValueError as exc:
            errors.append(str(exc))

    if args.check:
        errors.extend(validate_normalized_pages())
    errors.extend(validate_root_documents())
    errors.extend(validate_links())
    errors.extend(validate_encoding())

    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1

    distribution = Counter(problem.difficulty for problem in problems)
    action = "Validated" if args.check else "Generated indexes for"
    print(
        f"{action} {len(problems)} accepted problems "
        f"({distribution['Easy']} Easy, {distribution['Medium']} Medium, {distribution['Hard']} Hard)."
    )
    print(f"Roadmap: {count}; practice tracks: {', '.join(str(value) for value in track_counts.values())}")
    print(f"Attempts kept separate: {attempt_count}; duplicate problem numbers: 0")
    print("Metadata, generated indexes, internal links, and encoding passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
